### ISSUE TITLE
[Feature]: post editing not working

### ISSUE THREAD

**Issue by 777Prabhjot** [Sahilll15/Anonymous_social#1]
post editing feature not working properly

**Screen Shot**

<img width="939" alt="Screenshot 2023-08-22 150506" src="https://github.com/Sahilll15/Anonymous_social/assets/68184118/748b8bb5-442f-4f17-b875-3ba51e4dd3bc">

### **I would love to work on this**

**Comment by Sahilll15** [comment]
assigned to you!! check the problem and revert back what the issue ..ig your token was deleted or maybe depreciated

**Comment by 777Prabhjot** [comment]
@Sahilll15 backend apis are working fine i figured out that the problem is in the front-end for some reason after login localstorage.getItem('auth') not abled to get the token from the localstorage so the simple solution for this is to reload the page after user login i have already made changes in the front-end code please do check it out

**Comment by Sahilll15** [comment]
It would be good if you want to make the UI more user-friendly
